name: Java Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    
    # THE MATRIX (NEW!)
    strategy:
      matrix:
        java-version: [ '17', '21']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Now the robot dynamically chooses the version based on the matrix!
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Compile Java Files
        run: |
          mkdir -p bin
          javac -cp "lib/*" -d bin $(find src -name "*.java")

      - name: Inject and Test Database Password
        env:
          MY_DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: echo "Successfully loaded password."

      # We dynamically name the zip file so they don't overwrite each other!
      - name: Upload Compiled App as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bank-management-compiled-java-${{ matrix.java-version }}
          path: |
            bin/
            lib/